spring:

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/batch?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PWD:0319}
    driver-class-name: com.mysql.cj.jdbc.Driver
